[package]
name = "redis"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
bytes = "1.5.0"
log = "0.4.20"
env_logger = "0.10.1"
thiserror = "1.0.57"
dotenv = "0.15.0"
